[options]
http_interface = 0.0.0.0
http_port = 8069
proxy_mode = True
# workers = 5
# longpolling_port = 8072
workers = 0
server_wide_modules = base,web
data_dir = /opt/odoo/data
list_db = False
addons_path = /opt/odoo/repos/odoo/odoo/addons,/opt/odoo/repos/odoo/addons
    ,/opt/odoo/custom_addons
